name: Build iOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.8'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Create dummy .env.dev
        run: cp .env.example .env.dev

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign

      - name: Create iOS archive
        run: |
          cd build/ios/archive
          zip -r ios-archive.zip *

      - name: Upload iOS build
        uses: actions/upload-artifact@v3
        with:
          name: release-ios
          path: build/ios/archive/ios-archive.zip
